float64  timestamp  #时间戳
uint8 id		#导航id
float32  yaw         # 偏航角（0-359.99）
float32  pitch        # 俯仰角（-90-90）
float32  roll         # 横滚角（-180-180）
float32  wx         # 角速度x
float32  wy         # 角速度y
float32  wz         # 角速度z
float32  ax         # 加速度x
float32  ay         # 加速度y
float32  az         # 加速度z
float32  longitude        # 经度
float32  latitude         # 纬度
float32  height         # 高度
float32  eastvelocity         # 东向速度
float32  northvelocity        # 北向速度
float32  skyvelocity         # 天向速度
float32  process_time     # 进程处理时间

